name: ShellCheck
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck -x -S warning install.sh scripts/*.sh
